# INformações - Site
site_name: RoboConnection #Connecting the Robo Journey
site_url: https://residenciaticbrisa.github.io/03_Robotica/

# Informações - Repositório
repo_name: '03_Robotica'
repo_url: https://github.com/ResidenciaTICBrisa/03_Robotica

theme: readthedocs

nav:
  - Home: index.md
  - Instruções:
    - ROS: Instruções/ROS1.md
    - Robot Settings: Instruções/Robot_Settings.md