# INformações - Site
site_name: RoboConnection #Connecting the Robo Journey
site_url: https://residenciaticbrisa.github.io/03_Robotica/

# Informações - Repositório
repo_name: '03_Robotica'
repo_url: https://github.com/ResidenciaTICBrisa/03_Robotica

theme: readthedocs

nav:
  - Home: index.md
  - Instruções:
    - ROS: Instruções/ROS1.md
    - ROS2: ros2/general-instructions.md
      - Precompiled: ros2/installing-precompiled-packages.md
      - Compiling: ros2/compiling-for-amd64-based-systems.md
      - Compiling for SBCs: ros2/compiling-for-arm-based-systems.md
    - Robot Settings: Instruções/Robot_Settings.md
