# Informações - Site
site_name: RoboConnection #Connecting the Robo Journey
site_url: https://residenciaticbrisa.github.io/03_Robotica/

# Informações - Repositório
repo_name: 'RoboConnection'
repo_url: https://github.com/ResidenciaTICBrisa/03_Robotica

copyright: Copyright &copy; 2023 BRISA

theme:
  name: material
  features:
    - navigation.tabs
    #- navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share

    - content.tabs.link
    - content.code.annotation
    - content.code.copy

    - announce.dismiss
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: switch to dark mode
      primary: deep purple
      accent: cyan

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: switch to light mode
      primary: deep purple
      accent: cyan
  icon:
    logo: material/robot-industrial-outline
    repo: material/robot-industrial-outline
  favicon: assets/images/robo.png
  custom_dir: docs/overrides

extra_css:
  - stylesheets/style.css

extra_javascript:
  - javascripts/script.js

plugins:
  - search:
      lang:
        - pt
        - en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


nav:
  - Home: index.md
  - Primeiros Passos: Instruções/Maquina_Virtual.md
  - Trabalhando com o v4:
    - Introdução ao NAOqi: Instruções/NAOqi-overview_v4.md
    - Máquina Virtual com scripts: vms/ubuntu-14/README.md
    - NAO Flahser: Instruções/NAO_Flasher.md
    - SDK C++: Instruções/CPP_SDK_v4.md
    - Choregraphe: Instruções/Choregraphe_v4.md
  - Trabalhando com o v6:
    - Introdução ao NAOqi: Instruções/NAOqi-overview_v6.md
    - Máquina Virtual com scripts: vms/ubuntu-16/README.md
    - Robot Settings: Instruções/Robot_Settings.md
    - SDK C++: Instruções/CPP_SDK_v6.md
    - Choregraphe: Instruções/Choregraphe_v6.md
  - Extra:
    - ROS1:
      - Instruções: Instruções/ROS_1.md
      - General: ros1/general-instructions.md
      - Precompiled: ros1/installing-precompiled-packages.md
      - Compiling: ros1/compiling-for-amd64-based-systems.md
      - Compiling for SBCs: ros1/compiling-for-arm-based-systems.md
    - ROS2:
      - General: ros2/general-instructions.md
      - Precompiled: ros2/installing-precompiled-packages.md
      - Compiling: ros2/compiling-for-amd64-based-systems.md
      - Compiling for SBCs: ros2/compiling-for-arm-based-systems.md
  - Marcos: release/index.md
  - Equipe: sobre/equipe.md
  - Sobre: sobre/sobre.md
